// Generated by CoffeeScript 1.6.2
var f, someFunc;

someFunc = function() {
  return true;
};

if ((typeof module) === 'undefined') {
  f = {};
  f.someFunc = someFunc;
  this.fibonacci = f;
} else {
  exports.someFunc = someFunc;
}
