// Generated by CoffeeScript 1.3.3
(function() {

  chai.should();

  describe('A test suite', function() {
    describe('A string of fifteen letters', function() {
      var myString;
      myString = "Now is the time";
      it('should be of type string', function() {
        return myString.should.be.a('string');
      });
      return it('should have a length of 15', function() {
        return myString.should.have.length(15);
      });
    });
    return describe('An array of three items', function() {
      var array;
      array = [1, 2, 3];
      it('should be of type array', function() {
        return array.should.be.a('array');
      });
      it('should have a length of 3', function() {
        return array.should.have.length(3);
      });
      return it('should return -1 when a searched for item is not present', function() {
        return array.indexOf(4).should.equal(-1);
      });
    });
  });

}).call(this);
